### ISSUE TITLE
Separate RAW repo

### ISSUE THREAD

**Issue by toddmedema** [ExpeditionRPG/expedition-art#3]
Seeing as this gets used by the app, card creator and quest creator, which then all have to download 100's of MB of raw art assets... thoughts on splitting out all of the other art (old drafts, raw / editable files, etc) to a separate -art-raw or -art-meta repo? Would make maintenance more of a pain, so maybs not worth it at this point

**Comment by smartin015** [comment]
SG, let's make an `expedition-art-raw` repo or some such.

**Comment by toddmedema** [comment]
Thinking about this more, it would be nice to have some sort of official link between art and art-raw.... and I think I might have the ticket: git submodules - http://alx.github.io/gitbook/5_submodules.html

It's very similar to NPM modules, whereby there would be a clear symlink (one that could even be used by something like webpack to generate compressed assets into this repo from the raw assets in the other repo) - but, since it's outside of NPM modules, the raw files wouldn't get imported as part of the usual `npm install`
